### ISSUE TITLE
Error: Failed to require "chroma-js"

### ISSUE THREAD

**Issue by rsrini7** [noflo/noflo-image#15]
When i am trying samples, i am getting the error as shown in the screenshot. Do i need to install any chrome plugin ?

![image](https://cloud.githubusercontent.com/assets/5178105/8279291/dba9de10-18f0-11e5-9443-be1839da2247.png)

**Comment by misterr8472** [comment]
Same issue. Any ideas?

**Comment by jonnor** [comment]
Should be fixed by 2bf6afd64fd43776ce5cf06a87ff4bbe2677acb5, but won't hit `app.flowhub.io` until we re-deploy.

**Comment by jonnor** [comment]
As long as you are not using `image/GetHistogram` or `image/ExtractSaturation` components under browser, it should not effect other usage.

**Comment by misterr8472** [comment]
Hey,

I simply re-acquired chroma.js via npm once more and both errors
disappeared magically. Thanks so much for the quick response!!

While I am at it, may I ask another potentially silky question. Can I get
the graph editor visible in the browser to also show up as standalone
application on my desktop? Seems to be all commandine in tutorials.

Thanks!
A

**Comment by jonnor** [comment]
By the graph editor, I assume you mean Flowhub. You can install the Chrome app, then you get pretty nice desktop integration: https://chrome.google.com/webstore/detail/flowhub/aacpjichompfhafnciggfpfdpfododlk?hl=en

**Comment by misterr8472** [comment]
That seems to be the one :D

Thanks!

On 27 August 2015 at 16:07, Jon Nordby <notifications@github.com> wrote:

> By the graph editor, I assume you mean Flowhub. You can install the Chrome
> app, then you get pretty nice desktop integration:
> https://chrome.google.com/webstore/detail/flowhub/aacpjichompfhafnciggfpfdpfododlk?hl=en
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/noflo/noflo-image/issues/15#issuecomment-135463311>.
>



-- 
www.adrianlausch.com
+447506120677
